### ISSUE TITLE
help data - angularjs

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/client#210]
### I'm getting the date, but I can not play on my ngRepeat

my code:

`auditoriaService.find().then(function(res) {
            console.log(res);
            vm.audit = res.data;
        })
` 

no ng-repeat I call it that:

`<ul><li ng-repeat="a in vm.audit">{{a.name}}</li></ul>`

**Comment by daffl** [comment]
This is a framework question that is probably better answered on Slack or Stackoverflow.
