### ISSUE TITLE
Socket.io on iOS and Firefox don't work

### ISSUE THREAD

**Issue by vodniciarv** [feathersjs/client#225]
Hello, 
this is my connection code on client:
`this._socket = io(environment.domain.api, {
    transports: ['websocket'],
    forceNew: true
});`
`this._socket.on('reconnect_attempt', () => {
    this._socket.io.opts.transports = ['polling', 'websocket'];
});`
`this._feathers = feathers();                      // init Feathers`
`this._feathers.configure(hooks());                // add hooks plugin`
`this._feathers.configure(feathersRx({             // add feathers-reactive plugin
    idField: 'id'
}));`
`this._feathers.configure(socketio(this._socket)); // add socket.io plugin`
`this._feathers.configure(authentication({         // add authentication plugin
    storage: window.localStorage
}));`
I use Angular 5.
In Chrome and Chrome on Android, this code work well, on firefox - don't work.
Someone knows why?

**Comment by daffl** [comment]
Are you getting any error messages?

**Comment by vodniciarv** [comment]
Yes:
![screenshot_4](https://user-images.githubusercontent.com/14403446/34406943-6cc9001c-ebc4-11e7-85ee-0ea674ef8331.png)
![screenshot_5](https://user-images.githubusercontent.com/14403446/34406944-6ce89436-ebc4-11e7-8c87-d0bdb028fd3f.png)

**Comment by vodniciarv** [comment]
Site url is leo.md

**Comment by vodniciarv** [comment]
the problem was not in the socket's

**Comment by vodniciarv** [comment]
[https://github.com/angular/angular/issues/6531](https://github.com/angular/angular/issues/6531)
