### ISSUE TITLE
Feathers client now working with HTTPS self signed certs

### ISSUE THREAD

**Issue by jhendrick** [feathersjs/client#250]
Could very possibly be a user error, but I'm stumped here and can't figured out a solution:

I have configured my feathers server to use HTTPS with a self signed cert.  This works and from my react-native client code running on device I can successfully use feathers client to connect to the server over HTTPS.  I've also created a test suite using mocha which leverages feathers-client to execute a set of regression scripts.  When the server is configured to use HTTPS these fail, but work fine via HTTP.  The feather-client setup code is the same in both instances, only difference seems to be that I'm running the mocha test cases from the command line.

Any idea?  Happy to share the configuration files and/or test files if it will help to clarify. 

Node.js: v6.11.0
  "dependencies": {
    "feathers-authentication-client": "^0.3.3",
    "feathers-client": "^2.4.0",
    "feathers-rest": "^1.8.0",
    "native-base": "^2.3.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.2",
    "react-native-list-view-select": "^1.0.4",
    "react-native-modal": "^5.0.0",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-phone-input": "^0.1.9",
    "react-native-secure-key-store": "^1.0.8",
    "react-native-twilio-programmable-voice": "^3.2.0",
    "react-navigation": "^1.0.0-beta.27",
    "superagent": "^3.6.0",
    "tipsi-stripe": "^3.7.1"
.....
"devDependencies": {
 "mocha": "^3.5.3"

**Comment by daffl** [comment]
Depending on the transport you will have to configure it to not reject unauthorized certificated. You can find a test using Axios at https://github.com/feathersjs/express/blob/master/test/index.test.js#L230. The settings will be similar for other HTTP libraries.

**Comment by jhendrick** [comment]
Thanks @daffl, I've configured my server with those params, here is my feathers server code:

const logger = require('./logger/timestamplogger');
const feathersApp = require('./app');
const app = require('./app');
const port = app.get('port');
const fs = require('fs');
const https  = require('https');

const cwd = process.cwd();

const server = https.createServer({
  key: fs.readFileSync(cwd + '/cert/privatekey.pem'),
  cert: fs.readFileSync(cwd + '/cert/cert.pem'),
  requestCert: false,
  rejectUnauthorized: false
}, app).listen(port);

// Call app.setup to initialize all services and SocketIO
app.setup(server);

process.on('unhandledRejection', (reason, p) =>
  logger.error('Unhandled Rejection at: Promise ', p, reason)
);

server.on('listening', () =>
  logger.info(`Feathers application started on ${feathersApp.get('host')}:${port}`)
);

Still no luck when connecting from my client command line tests.

**Comment by daffl** [comment]
I meant to configure the client HTTTP transport accordingly. I'm not sure if those settings are required on the server.

**Comment by jhendrick** [comment]
Thanks you @daffl.  Fully admit this was user error.  Got it resolved now.

Changed feathers client test code using Socket.io from:
const socket = io(feathersUrl, {transports:['websocket']});
to
const socket = io(feathersUrl, {transports:['websocket'], rejectUnauthorized: false});

Thank you for the quick help.  Very much appreciated, had me stumped for a number of days.
