### ISSUE TITLE
Can't capture event on client side

### ISSUE THREAD

**Issue by kbychkov** [feathersjs/client#253]
Hello! I experienced some problems with catching service events on the client in my app. Therefore I've made a [simple feathers app](https://github.com/kbychkov/feathers-events) to reproduce the case.

I generated a simple `todos` service and made client-side [page](https://github.com/kbychkov/feathers-events/blob/master/public/index.html) using [example](https://github.com/feathersjs/client). The client calls `create` method of the service and should recieve `created` event. Unfortunately that doesn't work. 

What do I wrong?

**Comment by daffl** [comment]
The channels set up in a generated application __by default only publish to authenticated users__. You can modify this behaviour by changing https://github.com/kbychkov/feathers-events/blob/master/src/channels.js#L47 from `return app.channel('authenticated');` to `return app.channel('authenticated', 'anonymous');` but that should only be used for testing purposes.

This is also explained in the [real-time APIs basics guide](https://docs.feathersjs.com/guides/basics/real-time.html) and the [chat application guide](https://docs.feathersjs.com/guides/chat/readme.html).
