### ISSUE TITLE
I got error from NuxtJS when I use FeathersJS client V3

### ISSUE THREAD

**Issue by lagmanzaza** [feathersjs/client#260]
### Actual behavior
<img width="822" alt="screen shot 2561-05-21 at 22 21 40" src="https://user-images.githubusercontent.com/5283709/40315792-90e6938a-5d46-11e8-8f78-323e70247772.png">

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/authentication-client": "^1.0.2",
    "@feathersjs/feathers": "^3.1.5",
    "@feathersjs/socketio-client": "^1.1.0",

**NodeJS version**:
v8.10.0

**Operating System**:
MacOS

**Comment by lagmanzaza** [comment]
So now I can fix it by downgrading  feathersJS client version

**Comment by daffl** [comment]
You can also fix it by [actually upgrading](https://docs.feathersjs.com/migrating.html) in [this case](https://docs.feathersjs.com/migrating.html#client-side-feathers) `require('@feathersjs/socketio-client` should do it.

**Comment by lagmanzaza** [comment]
I used new FeathersJS client on NuxtJS but it doesn't work

**Comment by daffl** [comment]
It does need the new version on the server as well.

**Comment by lagmanzaza** [comment]
Yes, sir, I use the new version.
But it doesn't work when I use client lib on Nuxt
