### ISSUE TITLE
service times out when sending any request to the server, not on localhost

### ISSUE THREAD

**Issue by frastlin** [feathersjs/client#264]
Hello,
I'm trying to get a super simple server up and running and:
http://ec2-34-220-168-52.us-west-2.compute.amazonaws.com:8080/

The app object is called hatespeech. Whenever one types hatespeech.find().then(d=>console.log(JSON.stringify(d.data))
The error shows:
Unhandled promise rejection Object { type: "FeathersError", name: "Timeout", message: "Timeout of 5000ms exceeded calling …", code: 408, className: "timeout", data: Object, errors: Object, stack:

The exact same code runs on my computer and localhost. I have the firewall to accept all 8080 traffic.
I am sure this is a very newbie bug, but I can't seem to figure out how to access the methods on the objects outside of localhost.

The user should receive a blank array [] when doing hatespeech.find().

**Comment by daffl** [comment]
Your socket is instantiated with `var socket = io('http://localhost:8080');` it has to either be `var socket = io();` which will work for both cases or `var socket = io(http://ec2-34-220-168-52.us-west-2.compute.amazonaws.com:8080/);` in production.

**Comment by frastlin** [comment]
Thank you, fixed it right away!
