### ISSUE TITLE
IE11: TypeError: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by winchell** [feathersjs/client#270]
Wasn't expecting to see this in IE11 based on the manual:

> @feathersjs/client is a module that bundles the separate Feathers client-side modules into one providing the code as ES5 which is compatible with modern browsers (IE10+).

![capture](https://user-images.githubusercontent.com/425064/43124820-12dfa44a-8edd-11e8-9c76-6737c74ed426.PNG)

```
  "dependencies": {
    "@feathersjs/client": "github:feathersjs/client",
    "ajv": "^6.5.2",
    "ajv-keywords": "^3.2.0",
    "feathers-reactive": "^0.7.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "prop-types": "^15.6.0",
    "socket.io-client": "^2.0.4"
  },
```

**Comment by daffl** [comment]
Feathers requires an ES6 polyfill as shown in the [in the __Important__ section of this part of the documentation](https://docs.feathersjs.com/api/client.html#feathersjsclient):

> The Feathers client libraries come transpiled to ES5 and require ES6 shims either through the babel-polyfill module or by including core.js in older browsers e.g. via <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.1.4/core.min.js"></script>

**Comment by winchell** [comment]
Thanks! I was confused. ```import 'core-js';``` is probably a big hammer but that fixed the issue.
